### PR TITLE
biographical and capstone file added

### PR DESCRIPTION
**Pull request by smescarzaga**

### CODE REVIEW

**Comment by cklunch** [comment]
Content looks great! The markdown formatting didn't work quite right, I think you need to modify from
"##Words##"
to
"## Words"
without the quotation marks, I just included them so it wouldn't be formatted in this comment.
Try updating and adding to the pull request.

**Comment by smescarzaga** [comment]
Great, thanks for the heads-up. I fixed the syntax errors and went through
the steps again via the git bash shell. I hope I did that correctly.

**Comment by cklunch** [comment]
Looking better, still needs a space between the # and the titles. You can check the formatting as you go by either viewing the file on github online, or making your edits in a markdown editor, that might help.

**Comment by cklunch** [comment]
Got it!

**Pull request merged**
