### PR TITLE
Add Bailey-Tim.md introduction markdown file to repo

### PR DESCRIPTION
**Pull request by purpletreevole**

### CODE REVIEW

**Comment by cklunch** [comment]
Content looks good! The markdown formatting didn't work quite right in a few places, a couple of headers and a couple of paragraphs that ended up as code blocks. Check against a markdown cheat sheet or in a markdown editor, and add another commit to this pull request. Thanks!

**Comment by purpletreevole** [comment]
Sorry about that.
I will try to fix it.

Tim

**Comment by purpletreevole** [comment]
Improved formatting

**Comment by cklunch** [comment]
Looks good!

**Pull request merged**
