### PR TITLE
Commit of RGB assignment

### PR DESCRIPTION
**Pull request by purpletreevole**
RGB assignment submission

### CODE REVIEW

**Comment by cklunch** [comment]
Looking good! Can you also create a pdf version and add it to the pull request?

**Comment by purpletreevole** [comment]
Will do

**Comment by purpletreevole** [comment]
Adding pdf of rgb assignment to shared repo

**Comment by purpletreevole** [comment]
adding pdf of rgb assignment

**Comment by purpletreevole** [comment]
Hi Claire
I am a little confused about whether I have synced my commits properly. I
believe that I have added the pdf to the repo and it is waiting approval to
merge with the master. It seems like the two commits are staged together.
Thank you for your help.
Tim

**Comment by cklunch** [comment]
Yep, it's all set! When you have a pull request pending and you make more commits, they get added to the same pull request. Merging them in now.

**Comment by purpletreevole** [comment]
Thank you

**Pull request merged**
